version: '3.8'
services:
  triton-server:
    image: nvcr.io/nvidia/tritonserver:23.11-py3
    container_name: triton_server
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./model_repository:/models
    command: ["tritonserver", "--model-repository=/models", "--log-verbose=1"] 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
