model:
  name: microsoft/deberta-v3-small
  dropout: 0.5
  freeze_backbone: false

data:
  csv_path: /home/toomuch/mlops-course/lightning/demo-feedback-prize/data/train.csv
  val_size: 0.2
  dataloader_num_wokers: 0
  batch_size: 8
  text_max_length: 512

optimizer:
  learning_rate: 2e-5
  weight_decay: 0.01

scheduler:
  num_warmup_steps: 500
  num_training_steps: 5000

train:
  num_epochs: 3
  use_amp: false
  grad_accum_steps: 4

labels:
  - cohesion
  - syntax
  - vocabulary
  - phraseology
  - grammar
  - conventions
