version: '3.7'

services:
  mlflow_serving:
    image: my_model_image
    ports:
      - "13414:8080"
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 16G
